export const userActionTypes = {
    CHANGE_USER_INFO : 'CHANGE_USER_INFO',
    CHANGE_USER_AUTH_ACCESS : 'CHANGE_USER_AUTH_ACCESS',
    CHANGE_USER_AUTH_REFRESH : 'CHANGE_USER_AUTH_REFRESH',
    CLEAR_USER_INFO : 'CLEAR_USER_INFO',
}