export const helperTypes = {
    SET_SELECTED_IMAGES_STATE : 'SET_SELECTED_IMAGES_STATE',
    SET_CREATE_POST : 'SET_CREATE_POST',
    SET_CHANGE_SETTINGS : 'SET_CHANGE_SETTINGS',
    SET_FEED_REFS : 'SET_FEED_REFS',
    CLEAR_HELPER : 'CLEAR_HELPER'
}